import "./globals.css";
import SmoothScroll from "@/components/shared/SmoothScroll";
import CustomCursor from "@/components/shared/CustomCursor";
import WhatsAppButton from "@/components/shared/WhatsAppButton";

import { siteConfig } from "@/config/site";

export const metadata = {
  metadataBase: new URL("https://renginyazilim.com"),
  title: {
    default: "Diyarbakır Web Tasarım ve Kurumsal Yazılım Şirketi | Rengin Yazılım",
    template: `%s | ${siteConfig.name}`,
  },
  description: "Diyarbakır esnaf ve firmalarına özel mobil uyumlu kurumsal web sitesi, e-ticaret sitenizi kurun hizmetleri ve yazılım çözümleri. Hemen teklif alın!",
  keywords: [
    "diyarbakır web tasarım", "diyarbakir web tasarim",
    "diyarbakır web sitesi yapımı", "diyarbakir web sitesi yapimi",
    "diyarbakır e-ticaret", "diyarbakir e-ticaret",
    "diyarbakır kurumsal web sitesi", "diyarbakir kurumsal web sitesi",
    "diyarbakır yazılım şirketleri", "diyarbakir yazilim sirketleri",
    "diyarbakır esnaf web sitesi fiyatları",
    "diyarbakır avukat web sitesi",
    "diyarbakır emlak web sitesi",
    "diyarbakır doktor web sitesi",
    "diyarbakır inşaat firması web tasarım",
    "diyarbakır restoran ve kafe web sitesi",
    "diyarbakır rent a car web sitesi",
    "diyarbakır güzellik merkezi web tasarımı",
    "diyarbakır otel ve turizm web sitesi",
    "diyarbakır e-ticaret sitesi kurma",
    "diyarbakır seo ajansı", "diyarbakir seo",
    "diyarbakır dijital pazarlama",
    "diyarbakır kurumsal kimlik ve logo tasarımı",
    "diyarbakır özel yazılım", "diyarbakir ozel yazilim",
    "diyarbakır mobil uygulama geliştirme",
    "diyarbakır profesyonel web ajansı",
    "diyarbakır oto yıkama web sitesi",
    "diyarbakır oto yıkama yazılımı",
    "diyarbakır halı yıkama yazılımı",
    "diyarbakır eczane web sitesi",
    "diyarbakır hastane web sitesi",
    "diyarbakır poliklinik web tasarım",
    "diyarbakır psikolog web sitesi",
    "diyarbakır diyetisyen web tasarım",
    "diyarbakır spor salonu yazılımı",
    "diyarbakır fitness web sitesi",
    "diyarbakır cafe adisyon sistemi",
    "diyarbakır paket servis yazılımı",
    "diyarbakır pideci web sitesi",
    "diyarbakır fırın web tasarım",
    "diyarbakır pastane e-ticaret",
    "diyarbakır kasap e-ticaret sitesi",
    "diyarbakır manav online sipariş",
    "diyarbakır market e-ticaret sitesi",
    "diyarbakır sanal pos entegrasyonu",
    "diyarbakır kargo entegrasyonu",
    "diyarbakır muhasebe entegrasyonu",
    "diyarbakır pazar yeri entegrasyonu",
    "diyarbakır trendyol entegrasyonu",
    "diyarbakır hepsiburada entegrasyonu",
    "diyarbakır b2b portalı",
    "diyarbakır b2c portal",
    "diyarbakır crm programı",
    "diyarbakır erp programı",
    "diyarbakır ön muhasebe",
    "diyarbakır stok takip programı",
    "diyarbakır depo yönetim sistemi",
    "diyarbakır nakliye takip yazılımı",
    "diyarbakır kurye takip sistemi",
    "diyarbakır taksi durağı web sitesi",
    "diyarbakır düğün salonu rezervasyon sistemi",
    "diyarbakır organizasyon şirketi sitesi",
    "diyarbakır çilingir web sitesi",
    "diyarbakır elektrikçi web tasarım",
    "diyarbakır tesisatçı web sitesi",
    "diyarbakır boyacı web sitesi",
    "diyarbakır kombi servis web sitesi",
    "diyarbakır beyaz eşya servisi web sitesi",
    "diyarbakır klima servisi web tasarım",
    "diyarbakır oto tamir web sitesi",
    "diyarbakır oto ekspertiz web tasarım",
    "diyarbakır sigorta acentesi web sitesi",
    "diyarbakır tercüme bürosu web sitesi",
    "diyarbakır güvenlik şirketi web tasarım",
    "diyarbakır temizlik firması sitesi",
    "diyarbakır eğitim kurumu web sitesi",
    "diyarbakır anaokulu web sitesi",
    "diyarbakır kreş web tasarım",
    "diyarbakır özel okul web tasarım",
    "diyarbakır dershane web sitesi",
    "diyarbakır kolej web sitesi",
    "diyarbakır sürücü kursu yazılımı",
    "diyarbakır dil kursu web sitesi",
    "diyarbakır kpss kursu web sitesi",
    "diyarbakır özel ders web sitesi",
    "diyarbakır nakliyat web sitesi",
    "diyarbakır lojistik web tasarım",
    "diyarbakır tekstil firması web sitesi",
    "diyarbakır tekstil fabrikası web sitesi",
    "diyarbakır toptancı web tasarım",
    "diyarbakır ihracat web sitesi",
    "diyarbakır ithalat firması web tasarım",
    "diyarbakır fuar stand tasarım web sitesi",
    "diyarbakır reklam ajansı web sitesi",
    "diyarbakır matbaa web sitesi",
    "diyarbakır promosyon ürünleri e-ticaret",
    "diyarbakır tabela firması web tasarım",
    "diyarbakır mobilya mağazası e-ticaret",
    "diyarbakır beyaz eşya e-ticaret sitesi",
    "diyarbakır kuyumcu e-ticaret sitesi",
    "diyarbakır kuyumcu e-ticaret ve stok",
    "diyarbakır saatçi e-ticaret",
    "diyarbakır optik web sitesi",
    "diyarbakır kırtasiye e-ticaret",
    "diyarbakır hırdavat e-ticaret",
    "diyarbakır yapı market e-ticaret sitesi",
    "diyarbakır camcı web sitesi",
    "diyarbakır mobilya imalat web tasarım",
    "diyarbakır asansör firması web sitesi",
    "diyarbakır pvc pencere web tasarım",
    "diyarbakır güneş enerjisi firması web",
    "diyarbakır jeneratör firması web tasarım",
    "diyarbakır çiçekçi e-ticaret sitesi",
    "diyarbakır petshop e-ticaret",
    "diyarbakır veteriner kliniği yazılımı",
    "diyarbakır diş kliniği web tasarım",
    "diyarbakır veteriner web sitesi",
    "diyarbakır mimarlık ofisi web sitesi",
    "diyarbakır muhasebeci web sitesi",
    "diyarbakır mali müşavir web tasarım",
    "diyarbakır temizlik şirketi web sitesi",
    "diyarbakır halı yıkama web tasarım",
    "diyarbakır spor salonu web sitesi",
    "diyarbakır kuaför web tasarım",
    "diyarbakır fotoğrafçı web sitesi",
    "diyarbakır dernek ve vakıf web sitesi",
    "diyarbakır haber sitesi kurma",
    "diyarbakır blog sitesi yapımı",
    "diyarbakır google ads yönetimi",
    "diyarbakır sosyal medya danışmanlığı",
    "diyarbakır instagram reklam yönetimi",
    "kayapınar web tasarım", "kayapınar yazılım şirketi",
    "yenişehir web tasarım", "yenişehir e-ticaret",
    "ofis web tasarım", "ofis yazılım firması",
    "bağlar web tasarım", "bağlar web sitesi yapımı",
    "sur web tasarım diyarbakır",
    "diyarbakır fabrika web sitesi",
    "diyarbakır osb web tasarım",
    "diyarbakır sanayi sitesi web tasarım",
    "diyarbakır oto yedek parça e-ticaret",
    "diyarbakır medikal firma web sitesi",
    "diyarbakır poliklinik yazılımı",
    "diyarbakır estetik merkezi web sitesi",
    "diyarbakır diyetisyen web sitesi",
    "diyarbakır psikiyatri web sitesi",
    "diyarbakır diş hekimi web sitesi",
    "diyarbakır güzellik salonu randevu sistemi",
    "diyarbakır spa merkezi web sitesi",
    "diyarbakır hamam web sitesi",
    "diyarbakır kuru temizleme web sitesi",
    "diyarbakır kargo şirketi web tasarım",
    "diyarbakır evden eve nakliyat web sitesi",
    "diyarbakır asansörlü taşımacılık web sitesi",
    "diyarbakır vinç kiralama web sitesi",
    "diyarbakır iş makinesi kiralama sitesi",
    "diyarbakır hırdavat toptancısı web sitesi",
    "diyarbakır inşaat malzemeleri e-ticaret",
    "diyarbakır boya firması web sitesi",
    "diyarbakır tesisat firması web tasarım",
    "diyarbakır elektrikçi web sitesi",
    "diyarbakır mobilya dekorasyon web sitesi",
    "diyarbakır iç mimarlık ofisi web sitesi",
    "diyarbakır peyzaj firması web tasarım",
    "diyarbakır güvenlik kamera sistemleri web sitesi",
    "diyarbakır alarm sistemleri web sitesi",
    "diyarbakır asansör montaj web sitesi",
    "diyarbakır su arıtma firması web sitesi",
    "diyarbakır temizlik ürünleri e-ticaret",
    "diyarbakır kozmetik e-ticaret",
    "diyarbakır giyim mağazası e-ticaret",
    "diyarbakır butik e-ticaret sitesi",
    "diyarbakır tesettür giyim e-ticaret",
    "diyarbakır ayakkabı mağazası e-ticaret",
    "diyarbakır takı ve aksesuar e-ticaret",
    "diyarbakır bebek giyim e-ticaret",
    "diyarbakır oyuncak mağazası e-ticaret",
    "diyarbakır züccaciye e-ticaret sitesi",
    "diyarbakır çeyiz mağazası web sitesi",
    "diyarbakır perdeciler web sitesi",
    "diyarbakır halı saha rezervasyon sistemi",
    "diyarbakır yüzme havuzu web sitesi",
    "diyarbakır spor kulübü web sitesi",
    "diyarbakır cafe web sitesi",
    "diyarbakır nargile kafe web tasarım",
    "diyarbakır restoran sipariş sistemi",
    "diyarbakır tantunici web sitesi",
    "diyarbakır kebapçı web sitesi",
    "diyarbakır lahmacun sipariş sitesi",
    "diyarbakır çiğköfteci web sitesi",
    "diyarbakır dönerci web sitesi",
    "diyarbakır pastane sipariş sitesi",
    "diyarbakır tatlıcı web sitesi",
    "diyarbakır fırıncı web tasarım",
    "diyarbakır kasap web sitesi",
    "diyarbakır şarküteri e-ticaret",
    "diyarbakır kuruyemiş e-ticaret sitesi",
    "diyarbakır aktar e-ticaret sitesi",
    "diyarbakır kırtasiye toptancısı web sitesi",
    "diyarbakır kitapçı e-ticaret",
    "diyarbakır matbaa ve baskı web sitesi",
    "diyarbakır promosyon ürünleri web sitesi",
    "diyarbakır reklam tabela web sitesi",
    "diyarbakır fuar organizasyon web sitesi",
    "diyarbakır kongre ve toplantı web sitesi",
    "diyarbakır tercüme bürosu web tasarım",
    "diyarbakır sigorta acentesi yazılımı",
    "diyarbakır oto kiralama yazılımı",
    "diyarbakır rent a car rezervasyon sistemi",
    "diyarbakır seyahat acentesi web sitesi",
    "diyarbakır hac ve umre organizasyon sitesi",
    "diyarbakır otel rezervasyon yazılımı",
    "diyarbakır butik otel web tasarım",
    "diyarbakır apart otel web sitesi",
    "diyarbakır pansiyon web tasarım"
  ],
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: "Diyarbakır Web Tasarım | Rengin Yazılım",
    description: "İşletmenizi dijitale taşıyın. Profesyonel web sitesi yapımı ve e-ticaret çözümleri.",
    url: "https://renginyazilim.com",
    siteName: "Rengin Yazılım",
    locale: "tr_TR",
    type: "website",
    images: [
      {
        url: "/og-image.webp",
        width: 1200,
        height: 630,
        alt: `${siteConfig.name} Logo`,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Diyarbakır Web Tasarım | Rengin Yazılım",
    description: "İşletmenizi dijitale taşıyın. Profesyonel web sitesi yapımı ve e-ticaret çözümleri.",
    images: ["/og-image.webp"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr" suppressHydrationWarning>
      <head>
        <meta name="color-scheme" content="light" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link
          href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400&display=swap"
          rel="stylesheet"
        />
      </head>
      <body suppressHydrationWarning>
        <SmoothScroll>
          <CustomCursor />
          <WhatsAppButton />
          <div className="relative z-10">
            {children}
          </div>
        </SmoothScroll>
      </body>
    </html>
  );
}
